### ISSUE TITLE
Looking for endpoints

### ISSUE THREAD

**Issue by jcalfee** [bancorprotocol/sdk#30]
Can you please provide more information about what I need to do to get these endpoints?

https://docs.bancor.network/sdk/sdk-api-reference#initialization

```js
const settings = {
    // optional, mandatory when interacting with the ethereum mainnet
    ethereumNodeEndpoint: '<ethereum node endpoint>',
    // optional, mandatory when interacting with the EOS mainnet
    eosNodeEndpoint: '<eos node endpoint>'
};
```

On the EOS side, some of the block producers still provide `/bp.json` files.  I did find one here: https://eosnation.io/bp.json and here https://eosauthority.com/bp.json .. In tried a few returned `api_endpoint` and `ssl_endpoint` URLs.  That TIP would be good in your docs.  I'm assuming your API will work with SSL, but a confirmation will help reduce confusion.

On the ETH side, I'm not sure what to use.  I finally found one to try: https://main-light.eth.linkpool.io/ but I'm getting an error.  What specifically am I looking for, it is any mainnet RPC URL?  Do you have some suggestions?

```js
> BancorSDK = require('bancor-sdk').SDK; settings = {ethereumNodeEndpoint: 'https://main-light.eth.linkpool.io/', eosNodeEndpoint: 'https://publicapi-mainnet.eosauthority.com'}; bancorSDK = await BancorSDK.create(settings)
Uncaught Error: Returned error: execution aborted (timeout = 5s)
    at Object.ErrorResponse (/bancor/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /bancor/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/bancor/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/bancor/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/bancor/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/bancor/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
```

**Comment by barakman** [comment]
@jcalfee : On ETH side, you can use `"https://mainnet.infura.io/v3/YourInfuraProjectId"`.

**Comment by jcalfee** [comment]
I see .. thanks
